title: Iglika Nikolova-Stoupak
description: Welcome to my personal page.
# baseurl: "" # the subpath of your site, e.g., /blog
url: "https://iglika88.github.io" # the base hostname & protocol for your site

theme: minima

exclude:
  - README.md

markdown: kramdown

author: Iglika Nikolova-Stoupak

# Social links (optional)
social_links:
  github: iglika88
  linkedin: iglika-nikolova-stoupak-71290029/
  youtube: monoglossia
