title: Iglika Nikolova-Stoupak
description: Welcome to my personal page.
theme: minima
url: "https://iglika88.github.io"

author: Iglika Nikolova-Stoupak

social_links:
  github: iglika88
  linkedin: iglika-nikolova-stoupak-71290029/
  youtube: monoglossia

